name: auto update nix flake
on:
  schedule:
    - cron: "0 */12 * * *"
  push:
    branches: [nixos]
    paths:
      - ".github/workflows/update-nix-flake.yaml"
permissions:
  contents: write
jobs:
  update-nix-flake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: "Import GPG key"
        id: import-gpg
        uses: crazy-max/ghaction-import-gpg@2dc316deee8e90f13e1a351ab510b4d5bc0c82cd # v7.0.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          fingerprint: 487F026936540E5D76FF712A6201116F67AD6FAC
      - uses: cachix/install-nix-action@96951a368ba55167b55f1c916f7d416bac6505fe # v31.10.3
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix flake update
      - uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
        with:
          commit_author: "hidehic0 <${{ steps.import-gpg.outputs.email }}>"
          commit_user_name: hidehic0
          commit_user_email: ${{ steps.import-gpg.outputs.email }}
          commit_message: "chore(deps): updated flake.lock"
          pull: true
